In [2]:
import pandas as pd
import numpy as np

In [5]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
df = pd.read_csv('covid_toy.csv')
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [6]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)
X_train

    age  gender  fever   cough     city
77    8  Female  101.0    Mild  Kolkata
29   34  Female    NaN  Strong   Mumbai
24   13  Female  100.0  Strong  Kolkata
49   44    Male  104.0    Mild   Mumbai
42   27    Male  100.0    Mild    Delhi
..  ...     ...    ...     ...      ...
46   19  Female  101.0    Mild   Mumbai
90   59  Female   99.0  Strong    Delhi
79   48  Female  103.0    Mild  Kolkata
72   83  Female  101.0    Mild  Kolkata
17   40  Female   98.0  Strong    Delhi

[80 rows x 5 columns]

## 1. Aam Zindagi

In [8]:
# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])
                                 
X_train_fever.shape

(80, 1)